language: csharp
script: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    rm -rf _gh_pages || exit 0
    mkdir _gh_pages
    cd _gh_pages
    mkdir assets
    git checkout -b gh-pages
    ls
    cd ..
    mono libs/GitHubPagesGenerator.exe -t "json api v1.3"
    cp -r assets/* _gh_pages/assets
    cd _gh_pages
    ls
    git add . --all
    git -c user.name='SaferpayDev' -c user.email='travis' commit -m "Updated Github pages"
    git push -f -q https://SaferpayDev:${GITHUB_API_KEY}@github.com/saferpay/jsonapi.git gh-pages 
    cd "$TRAVIS_BUILD_DIR"
  fi
